### ISSUE TITLE
Request for RWKV-CLIP-B/16 Model Weight

### ISSUE THREAD

**Issue by byougert** [deepglint/RWKV-CLIP#10]
First of all, thank you for your contributions, and congratulations on your paper being accepted!

I am currently researching in the field of vision and language processing, and I believe the RWKV-CLIP-B/16 model could be very beneficial to my ongoing work. Therefore, I would like to inquire if it is possible to obtain the pre-trained weights for the RWKV-CLIP-B/16 version?

Looking forward to your assistance.

**Comment by kaichengyang0828** [comment]
Due to CVPR's deadline, we plan to open-source the required weights during the second half of this month. Thank you for your attention.

**Comment by byougert** [comment]
Thanks for your response! 
Best wishes for your submission. 
Looking forward to the open-sourcing of the weights.
