### ISSUE TITLE
Missing requirements.txt File

### ISSUE THREAD

**Issue by imljn** [deepglint/RWKV-CLIP#3]
Thank you for sharing this awesome paper as well as the code.
The project does not include a requirements.txt file, making setting up the development environment a bit challenging. Could the project maintenance team provide it? Your time and assistance are greatly appreciated!

**Comment by jasonYpretty** [comment]
For your reference:
numpy
torch 
nvidia-dali-cuda110 % https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html
dali
ftfy
regex
ninja
mmcv-full % mmcv-2 works, some minor adjustments need to be made when importing...
mmcls % mmcls-0.25.0 works

**Comment by kaichengyang0828** [comment]
I'm sorry for the negligence in our work. We have added the requirements.txt and more detailed instructions for environment setup. Thanks for your attention.
