### ISSUE TITLE
一些疑问：关于中文，输入长度，搜索

### ISSUE THREAD

**Issue by gg22mm** [deepglint/RWKV-CLIP#4]
这个支持中文吗？， 不知道这个支持多大长度输入的是多少？
做为 图片搜图 ，图片搜文， 文搜图，文搜文的向量库， 以后还会用来做图像生成么 ？ ~~

**Comment by kaichengyang0828** [comment]
为了和baseline公平比较，输入长度最大为77。受限于算力资源，目前RWKV-CLIP是在YFCC15M上进行预训练的，图文检索性能相较于海量数据(LAION400M\LAION2B等)训练的模型还有较大的差距，但是我们有尝试过RWKV-CLIP是可以做scaling的(参考appendix)
