### ISSUE TITLE
Thank you for your contribution. Please tell me how long it took you to train the model on 8 A100 GPUs?

### ISSUE THREAD

**Issue by Pengxiang-zhao** [deepglint/RWKV-CLIP#7]

**Comment by kaichengyang0828** [comment]
Due to the inherent flaws of the SSM model (such as Mamba, RWKV, etc., which train less efficiently with shorter input sequence lengths), we used 8 x A100(80G) to train RWKV-CLIP B/32 on YFCC15M, which took approximately 26 hours. Thanks for your attention!

**Comment by Pengxiang-zhao** [comment]
Thank you very much！
