### ISSUE TITLE
The dataset you uploaded in huggingface is in parquet format, what format did you convert it to during training, it doesn't seem to be reflected in the code.

### ISSUE THREAD

**Issue by Pengxiang-zhao** [deepglint/RWKV-CLIP#8]

**Comment by kaichengyang0828** [comment]
To utilize DALI for speeding up the training process, we use Mxnet to pack all the images and text tokens into a .rec file. You can refer to data2rec.py.  By the way, the dataset we uploaded on Hugging Face consists of raw images and text tokens from raw texts, synthetic captions, and descriptions generated by our framework, all of which have been tokenized by the CLIP tokenizer. Besides, I‘m certain that we have uploaded around 15 million image-text pairs, but I'm not sure why it only shows 13.4 million on the Hugging Face🤔️. If you encounter any issues with the downloaded data, please contact me promptly. Thanks for your attention!

**Comment by Pengxiang-zhao** [comment]
That means that the dataset you uploaded on huggingface has been labeled by your data pipeline and one of the three labels has been randomly selected as a label. then the dataset on huggingface is actually incomplete, there are only 13.4 million of them. I have downloaded your full dataset and haven't verified the number yet, I will contact you if I encounter any problems in the future. At the moment I'm looking at the individual parquet packages and it's the ones with about 10,000 data, so far it looks pretty normal.

**Comment by kaichengyang0828** [comment]
I‘m so sorry, after confirming with my colleague, I realized that the data uploaded on Hugging Face only includes the text descriptions generated by our framework. The original text and text generated by OFA are not included. All tokens have been encoded using the CLIP tokenizer. You can decode the tokens into original text using `from clip.simple_tokenizer import SimpleTokenizer as _Tokenizer`. If you have the overall statistical information on the dataset quantity later on, please kindly inform us if there are any issues. Thank you very much！

**Comment by Pengxiang-zhao** [comment]
So did you guys use the raw text and OFA generated text during training, I remember in the paper it was mentioned that it was randomly selected among the three. May I ask how I should complement the text of the dataset if I want to reproduce your work?

**Comment by kaichengyang0828** [comment]
Firstly, please provide me with the total number of image-text pairs. If the data we upload to Hugging Face is correct, we can then add a new file containing tokens of raw text and OFA-generated text. For more efficient communication, could you give me your wechat?

**Comment by Pengxiang-zhao** [comment]
sure, px18871208826
